apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-example
  name: kubernetes-start
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetes-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubernetes-example
    spec:
      containers:
      - image: acalderon88/kube-training:1.0.0
        name: kubernetes-start
        ports:
        - containerPort: 8080