apiVersion: v1
kind: Service
metadata:
  name: my-service-kubernetes
spec:
  selector:
    app: kubernetes-start
  ports:
    - name: http
      protocol: TCP
      port: 5555
      targetPort: 8080
  externalIPs:
    - 80.11.12.10