apiVersion: v1
kind: Service
metadata:
  name: my-service-kubernetes
spec:
  selector:
    app: kubernetes-start
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  clusterIP: 10.0.2.15
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127